### ISSUE TITLE
i can't install this package anymore

### ISSUE THREAD

**Issue by luizproenca** [ismaeldcom/react-native-build-config#8]
When i try to install this package using command "npm i ismaeldcom/react-native-build-config", receive the message: 

npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/ismaeldcom/react-native-build-config.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lproenca\AppData\Roaming\npm-cache\_logs\2019-07-17T17_27_35_687Z-debug.log

**Comment by maddijoyce** [comment]
Hi @luizproenca, is there any reason you’re trying to install from github and not npm?
The latest version is available using ‘npm i react-native-build-config’.

**Comment by luizproenca** [comment]
But the orientation in the npm site is to use this command:

![npm](https://user-images.githubusercontent.com/22194946/61475855-18d4d000-a962-11e9-8608-b752e7c9c076.png)


![cmd](https://user-images.githubusercontent.com/22194946/61475991-681b0080-a962-11e9-9493-a4c79396ee0e.png)

**Comment by ismaeldcom** [comment]
Hi @luizproenca, I think the error has nothing to do with the package maybe a common permission error with node in Windows. Can you upload the content of the .log file? We can try to help.

The error only happen with this package? You tried with `npm i react-native-build-config`?

@maddijoyce I'll update the install instruction to use npm as repository. When I make the package the company wanted to use github instead.

**Comment by luizproenca** [comment]
If I use the "npm i react-native-build-config" command the installation normally occurs.
The problem is that I am not in version 0.60 of react-native and so I need to use version 0.1.0 of react-native-build-config by following the installation guide.
And when I use the command "npm i react-native-build-config@0.1.0" I get the message:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'react-native-build-config@0.1.0' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose npm-session 2dd7b6e4c24ac451
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/react-native-build-config 1509ms
8 silly fetchPackageMetaData error for react-native-build-config@0.1.0 No matching version found for react-native-build-config@0.1.0
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 3640ms
11 verbose type version
12 verbose stack react-native-build-config: No matching version found for react-native-build-config@0.1.0
12 verbose stack     at pickManifest (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-pick-manifest\index.js:101:11)
12 verbose stack     at fetchPackument.then.packument (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:24:14)
12 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
12 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
12 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
12 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
12 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:694:18)
12 verbose stack     at _drainQueueStep (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:138:12)
12 verbose stack     at _drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
12 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5)
12 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
12 verbose stack     at runCallback (timers.js:705:18)
12 verbose stack     at tryOnImmediate (timers.js:676:5)
12 verbose stack     at processImmediate (timers.js:658:5)
13 verbose cwd C:\Users\lproenca\Documents\GitHub\OnibusCLNew
14 verbose Windows_NT 10.0.17763
15 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "react-native-build-config@0.1.0"
16 verbose node v10.16.0
17 verbose npm  v6.9.0
18 error code ETARGET
19 error notarget No matching version found for react-native-build-config@0.1.0
20 error notarget In most cases you or one of your dependencies are requesting
20 error notarget a package version that doesn't exist.
21 verbose exit [ 1, true ]

**Comment by ismaeldcom** [comment]
This error log show that react-native-build-config@0.1.0 does not exist in npm repository, this version wasn't release on npm. You can install from npm initial version 0.0.1.

You can try to install from npm using https instead of ssh, to avoid common node/windows permissions errors, using `npm i https://github.com/ismaeldcom/react-native-build-config#2af8fbb` you can install v0.1.0 with the `#2af8fbb` tag.

**Comment by luizproenca** [comment]
I used the mentioned command but the error still appearing.
![cmd2](https://user-images.githubusercontent.com/22194946/61532875-a4ea0480-aa01-11e9-9df5-efa708e780b5.png)

**Comment by ismaeldcom** [comment]
Can you attach the output of `git --version` in the shell?
